-- Database schema for Oracle Database 19c / 23ai (Oracle Cloud Free Autonomous DB).
-- Optional: the app creates these tables itself with DDL_AUTO=update (default for the "oracle" profile).
-- If you run this script, start the app with DDL_AUTO=none.

CREATE TABLE parking_lot (
    lot_id       VARCHAR2(12)  NOT NULL,
    name         VARCHAR2(100) NOT NULL,
    location     VARCHAR2(255) NOT NULL,
    open_time    VARCHAR2(5)   NOT NULL,   -- HH:mm, open_time = close_time means 24h
    close_time   VARCHAR2(5)   NOT NULL,
    CONSTRAINT pk_parking_lot PRIMARY KEY (lot_id)
);

CREATE TABLE parking_slot (
    id            VARCHAR2(19) GENERATED BY DEFAULT AS IDENTITY,
    lot_id        VARCHAR2(12) NOT NULL,
    slot_id       VARCHAR2(10) NOT NULL,
    vehicle_type  VARCHAR2(20) NOT NULL,
    status        VARCHAR2(20) NOT NULL,
    floor_level   NUMBER(10)   NOT NULL,
    CONSTRAINT pk_parking_slot PRIMARY KEY (id),
    CONSTRAINT uk_parking_slot_lot_slot UNIQUE (lot_id, slot_id),
    CONSTRAINT fk_parking_slot_lot FOREIGN KEY (lot_id) REFERENCES parking_lot (lot_id),
    CONSTRAINT ck_parking_slot_type CHECK (vehicle_type IN ('MOTORCYCLE', 'CAR', 'TRUCK')),
    CONSTRAINT ck_parking_slot_status CHECK (status IN ('AVAILABLE', 'OCCUPIED', 'RESERVED', 'MAINTENANCE'))
);

CREATE TABLE reservation (
    reservation_id       VARCHAR2(40)  NOT NULL,
    lot_id               VARCHAR2(12)  NOT NULL,
    slot_id              VARCHAR2(10)  NOT NULL,
    floor_level          NUMBER(10)    NOT NULL,
    vehicle_type         VARCHAR2(20)  NOT NULL,
    license_plate        VARCHAR2(20)  NOT NULL,
    customer_id          VARCHAR2(50)  NOT NULL,
    planned_start_time   TIMESTAMP(6)  NOT NULL,
    planned_end_time     TIMESTAMP(6)  NOT NULL,
    actual_start_time    TIMESTAMP(6),
    actual_end_time      TIMESTAMP(6),
    status               VARCHAR2(20)  NOT NULL,
    late_cancellation    NUMBER(1)     DEFAULT 0 NOT NULL,
    cancellation_reason  VARCHAR2(255),
    created_at           TIMESTAMP(6)  NOT NULL,
    CONSTRAINT pk_reservation PRIMARY KEY (reservation_id),
    CONSTRAINT ck_reservation_status CHECK (status IN ('PENDING', 'ACTIVE', 'COMPLETED', 'CANCELLED', 'NO_SHOW')),
    CONSTRAINT ck_reservation_window CHECK (planned_end_time > planned_start_time)
);

CREATE INDEX idx_reservation_slot_window ON reservation (lot_id, slot_id, planned_start_time, planned_end_time);
CREATE INDEX idx_reservation_customer ON reservation (customer_id);

CREATE TABLE rate_card (
    id                    VARCHAR2(19) GENERATED BY DEFAULT AS IDENTITY,
    vehicle_type          VARCHAR2(20) NOT NULL,
    hourly_rate           NUMBER(19,2) NOT NULL,
    daily_cap             NUMBER(19,2),
    overnight_surcharge   NUMBER(19,2),
    grace_period_minutes  NUMBER(10) DEFAULT 15 NOT NULL,
    CONSTRAINT pk_rate_card PRIMARY KEY (id),
    CONSTRAINT uk_rate_card_vehicle_type UNIQUE (vehicle_type)
);

CREATE TABLE parking_invoice (
    invoice_id                   VARCHAR2(40)  NOT NULL,
    reservation_id               VARCHAR2(40)  NOT NULL,
    customer_id                  VARCHAR2(50)  NOT NULL,
    billed_duration_minutes      NUMBER(19)    NOT NULL,
    base_amount                  NUMBER(19,2)  NOT NULL,
    overnight_surcharge_applied  NUMBER(19,2)  NOT NULL,
    discount_amount              NUMBER(19,2)  NOT NULL,
    total_amount                 NUMBER(19,2)  NOT NULL,
    generated_at                 TIMESTAMP(6)  NOT NULL,
    CONSTRAINT pk_parking_invoice PRIMARY KEY (invoice_id),
    CONSTRAINT uk_parking_invoice_reservation UNIQUE (reservation_id),
    CONSTRAINT fk_parking_invoice_reservation FOREIGN KEY (reservation_id) REFERENCES reservation (reservation_id)
);
